import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
import Login from "@/components/login/login";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Login/>
        {children}</body>
    </html>
  )
}
