import './globals.css'
import Login from "@/components/login/login";
import Provider from '../components/provider';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <Login>
            {children}
          </Login>
        </Provider>
      </body>
    </html>
  )
}
